smoothies:
  data-file: data/smoothies.yml

logging:
  file:
    name: ${smoothie.log.dir}/smoothie-maker.log
  logback:
    rollingpolicy:
      file-name-pattern: ${smoothie.log.dir}/smoothie-maker-%d{yyyy-MM-dd}.log
      max-history: 30
  level:
    root: INFO
    org.example.smoothies: DEBUG
